#+title: Scheduling

Lets see what are the different times in CPU scheduling.

   - Arrival Time:
     The time at which process enters the Ready Queue. Its a point of time.

   - Burst Time:
     Time required by a process to get executed by CPU. Its a duration.

   - Completion Time:
     The time at which a process gets completed. Its also a point of time.

   - Turnaround Time:
     Total duration of time for a process lifecycle. Its a duration.

     #+begin_src shell
       turnaround time = completion time - arrival time
     #+end_src

   - Waiting Time:
     A time spent by the process in Ready Queue to get the CPU time.

     #+begin_src shell
       wait time = turnaround time - burst time
     #+end_src

   - Response Time:
     The time at which a process gets a CPU for the first time. Its a point time.

     #+begin_src shell
      response time =  cpu for the firat time - arrival time
     #+end_src


** Scheduling Algorithm

Form now onwards we will use below short notations

|       |
|---+---|
|Process No.| PN |
|Arrival Time| AT|
|Burst Time| BT|
|Completion Time| CT|
|Turn Around Time | TAT|
|Waiting Time | WT|
|Response Time | RT|


- FCFS(First Come First Server):

| PT | AT | BT | CT | TAT | WT | RT|
|---+---+---+---+---+---
|   |   |   |   |   |  |
